"""changed publisher to author

Revision ID: 0d1b6ea14293
Revises: c90e5caeaa40
Create Date: 2023-04-20 12:00:00.915269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d1b6ea14293'
down_revision = 'c90e5caeaa40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_author', sa.String(), nullable=True))
    op.drop_column('books', 'book_publisher')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_publisher', sa.VARCHAR(), nullable=True))
    op.drop_column('books', 'book_author')
    # ### end Alembic commands ###
