"""Added Librariesls

Revision ID: a95da553f706
Revises: aa23f81cdbce
Create Date: 2023-04-18 18:45:14.663457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a95da553f706'
down_revision = 'aa23f81cdbce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
