"""Add tables

Revision ID: c90e5caeaa40
Revises: 17f217651cb9
Create Date: 2023-04-19 10:18:40.478878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c90e5caeaa40'
down_revision = '17f217651cb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('library_name', sa.String(), nullable=True),
    sa.Column('libray_address', sa.String(), nullable=True),
    sa.Column('library_city', sa.Integer(), nullable=True),
    sa.Column('library_state', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('owner_email', sa.String(), nullable=True),
    sa.Column('owner_phone', sa.Integer(), nullable=True),
    sa.Column('owner_address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_name', sa.String(), nullable=True),
    sa.Column('book_publisher', sa.String(), nullable=True),
    sa.Column('book_genre', sa.String(), nullable=True),
    sa.Column('book_pages', sa.Integer(), nullable=True),
    sa.Column('book_sales', sa.Integer(), nullable=True),
    sa.Column('book_price', sa.Integer(), nullable=True),
    sa.Column('book_rating', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('library_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    op.drop_table('owners')
    op.drop_table('libraries')
    # ### end Alembic commands ###
